version: "3.0"
volumes:
  volume_data:
networks:
  services-network:
    driver: bridge
services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_HOST: db
      DB_PASSWORD: root
      DB_NAME: building_db
      DB_PORT: 5432
    ports:
      - "8000:8000"
    restart: always
    networks:
      - services-network
  db:
    image: postgres
    volumes:
      - volume_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: building_db
      POSTGRES_PASSWORD: root
    networks:
      - services-network